import { useState } from 'react';
import {
  Folder,
  FileText,
  Download,
  Figma,
  Code2,
  FileCode,
  HardDrive,
  Upload,
  Search,
  ExternalLink,
  CheckCircle2,
  Sparkles,
  Eye,
  X,
  FileCheck
} from 'lucide-react';
import { ClientProject, ProjectFile } from '../../types';

interface ProjectFilesRepositoryProps {
  project: ClientProject;
  onAddFile: (file: Omit<ProjectFile, 'id' | 'uploadedAt'>) => void;
  onOpenDriveWorkspace: () => void;
}

export function ProjectFilesRepository({
  project,
  onAddFile,
  onOpenDriveWorkspace,
}: ProjectFilesRepositoryProps) {
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState('');
  const [isUploadModalOpen, setIsUploadModalOpen] = useState(false);
  const [previewingFile, setPreviewingFile] = useState<ProjectFile | null>(null);

  // Upload Form State
  const [uploadName, setUploadName] = useState('');
  const [uploadCategory, setUploadCategory] = useState<ProjectFile['category']>('PRD & Specs');
  const [uploadType, setUploadType] = useState<ProjectFile['type']>('pdf');
  const [uploadDescription, setUploadDescription] = useState('');

  const categories = [
    'All',
    'PRD & Specs',
    'UI/UX & Figma',
    'Architecture & Code',
    'Reports & QA',
    'Invoices & Legal'
  ];

  const filteredFiles = project.files.filter((file) => {
    const matchesCategory = selectedCategory === 'All' || file.category === selectedCategory;
    const matchesQuery =
      !searchQuery ||
      file.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      file.description?.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCategory && matchesQuery;
  });

  const getFileIcon = (file: ProjectFile) => {
    switch (file.type) {
      case 'figma':
        return <Figma className="w-5 h-5 text-pink-400" />;
      case 'code':
        return <Code2 className="w-5 h-5 text-emerald-400" />;
      case 'doc':
        return <FileCode className="w-5 h-5 text-blue-400" />;
      default:
        return <FileText className="w-5 h-5 text-purple-400" />;
    }
  };

  const handleUploadSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!uploadName.trim()) return;

    onAddFile({
      name: uploadName.trim(),
      category: uploadCategory,
      type: uploadType,
      size: '1.5 MB',
      url: '#',
      description: uploadDescription.trim() || 'Client-uploaded project asset.'
    });

    setUploadName('');
    setUploadDescription('');
    setIsUploadModalOpen(false);
  };

  const handleDownloadSimulated = (file: ProjectFile) => {
    if (file.url && file.url.startsWith('http')) {
      window.open(file.url, '_blank');
      return;
    }

    const sampleContent = `# ${file.name}
Project: ${project.projectName} (${project.accessCode})
Category: ${file.category}
Uploaded: ${file.uploadedAt}

Description:
${file.description || 'Confidential client deliverable generated by Vixora Systems.'}

---
Vixora Digital Hub — Engineering & AI Systems
All Intellectual Property Retained by ${project.company}`;

    const blob = new Blob([sampleContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', file.name.endsWith('.pdf') ? file.name.replace('.pdf', '.txt') : `${file.name}.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-200">
      {/* Top Header & Search Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-purple-900/30 pb-6">
        <div>
          <h2 className="text-xl sm:text-2xl font-bold text-white flex items-center gap-2.5">
            <Folder className="w-6 h-6 text-purple-400" />
            <span>Project Files & Deliverables Repository</span>
          </h2>
          <p className="text-xs sm:text-sm text-neutral-400 mt-1">
            Access blueprints, architecture specs, Figma prototypes, invoices, and verified security reports.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={onOpenDriveWorkspace}
            className="px-4 py-2.5 rounded-xl bg-purple-950/70 hover:bg-purple-900 text-purple-200 border border-purple-800/40 text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer"
          >
            <HardDrive className="w-4 h-4 text-emerald-400" />
            <span className="hidden sm:inline">Drive PRD Hub</span>
          </button>

          <button
            onClick={() => setIsUploadModalOpen(true)}
            className="px-4 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white text-xs font-semibold shadow-md shadow-purple-600/30 flex items-center gap-2 transition-all cursor-pointer"
          >
            <Upload className="w-4 h-4" />
            <span>Upload Asset</span>
          </button>
        </div>
      </div>

      {/* Category Pills & Search Field */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4">
        {/* Category Pills */}
        <div className="flex items-center gap-1.5 overflow-x-auto pb-2 sm:pb-0 scrollbar-none">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-3.5 py-1.5 rounded-xl text-xs font-semibold whitespace-nowrap transition-all cursor-pointer ${
                selectedCategory === cat
                  ? 'bg-purple-600 text-white shadow-md shadow-purple-600/30'
                  : 'bg-neutral-900/80 text-neutral-400 hover:text-white border border-neutral-800'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Search Field */}
        <div className="relative min-w-[240px]">
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search files by name..."
            className="w-full px-3.5 py-2 pl-9 rounded-xl bg-neutral-950 border border-purple-900/40 text-white placeholder-neutral-500 text-xs focus:outline-none focus:border-purple-400"
          />
          <Search className="w-3.5 h-3.5 text-neutral-500 absolute left-3 top-2.5" />
        </div>
      </div>

      {/* Files Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {filteredFiles.map((file) => (
          <div
            key={file.id}
            className="p-5 rounded-3xl bg-[#0E0722] border border-purple-900/40 hover:border-purple-500/50 transition-all flex flex-col justify-between space-y-4 group shadow-lg"
          >
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="p-2.5 rounded-2xl bg-purple-950/80 border border-purple-800/40">
                    {getFileIcon(file)}
                  </div>
                  <div>
                    <span className="text-[10px] font-mono text-purple-400 uppercase font-bold">
                      {file.category}
                    </span>
                    <div className="text-[10px] text-neutral-500 font-mono">
                      {file.uploadedAt} &bull; {file.size || 'Direct Link'}
                    </div>
                  </div>
                </div>

                {file.isDriveLinked && (
                  <span className="text-[10px] font-mono text-emerald-400 bg-emerald-950/60 px-2 py-0.5 rounded border border-emerald-500/30 flex items-center gap-1">
                    <HardDrive className="w-2.5 h-2.5" />
                    <span>Drive</span>
                  </span>
                )}
              </div>

              <h3 className="text-sm font-bold text-white group-hover:text-purple-300 transition-colors line-clamp-2">
                {file.name}
              </h3>

              {file.description && (
                <p className="text-xs text-neutral-400 line-clamp-2 leading-relaxed">
                  {file.description}
                </p>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex items-center gap-2 pt-2 border-t border-purple-900/20">
              <button
                onClick={() => setPreviewingFile(file)}
                className="flex-1 py-2 rounded-xl bg-purple-950/80 hover:bg-purple-900 text-purple-200 text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors cursor-pointer border border-purple-800/30"
              >
                <Eye className="w-3.5 h-3.5 text-purple-400" />
                <span>Preview</span>
              </button>

              <button
                onClick={() => handleDownloadSimulated(file)}
                className="p-2 rounded-xl bg-neutral-900 hover:bg-neutral-800 text-neutral-300 hover:text-white transition-colors cursor-pointer border border-neutral-800"
                title="Download / Open File"
              >
                {file.url && file.url.startsWith('http') ? (
                  <ExternalLink className="w-4 h-4 text-purple-300" />
                ) : (
                  <Download className="w-4 h-4 text-purple-300" />
                )}
              </button>
            </div>
          </div>
        ))}
      </div>

      {filteredFiles.length === 0 && (
        <div className="p-12 text-center rounded-3xl bg-[#0B061A] border border-purple-900/30 space-y-3">
          <FileText className="w-10 h-10 text-neutral-600 mx-auto" />
          <h4 className="text-base font-bold text-white">No files found matching criteria</h4>
          <p className="text-xs text-neutral-400 max-w-sm mx-auto">
            Try switching categories or upload a new asset to attach it to this project workspace.
          </p>
        </div>
      )}

      {/* Upload File Modal */}
      {isUploadModalOpen && (
        <div
          className="fixed inset-0 z-50 bg-black/80 backdrop-blur-sm flex items-center justify-center p-4"
          onClick={(e) => {
            if (e.target === e.currentTarget) setIsUploadModalOpen(false);
          }}
        >
          <div className="bg-[#0E0722] border border-purple-800/50 rounded-3xl p-6 sm:p-8 max-w-md w-full shadow-2xl space-y-5 animate-in fade-in duration-150">
            <div className="flex items-center justify-between border-b border-purple-900/30 pb-4">
              <h3 className="text-lg font-bold text-white flex items-center gap-2">
                <Upload className="w-5 h-5 text-purple-400" />
                <span>Upload Client Asset</span>
              </h3>
              <button
                onClick={() => setIsUploadModalOpen(false)}
                className="p-2 rounded-xl text-neutral-400 hover:text-white bg-neutral-900"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            <form onSubmit={handleUploadSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-mono text-purple-300 uppercase tracking-wider mb-1.5">
                  File Title / Asset Name
                </label>
                <input
                  type="text"
                  required
                  value={uploadName}
                  onChange={(e) => setUploadName(e.target.value)}
                  placeholder="e.g. Brand_Guidelines_2026.pdf"
                  className="w-full px-4 py-2.5 rounded-xl bg-neutral-950 border border-purple-900/50 text-white text-xs focus:outline-none focus:border-purple-400"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-mono text-purple-300 uppercase tracking-wider mb-1.5">
                    Category
                  </label>
                  <select
                    value={uploadCategory}
                    onChange={(e) => setUploadCategory(e.target.value as any)}
                    className="w-full px-3 py-2 rounded-xl bg-neutral-950 border border-purple-900/50 text-white text-xs focus:outline-none"
                  >
                    <option value="PRD & Specs">PRD & Specs</option>
                    <option value="UI/UX & Figma">UI/UX & Figma</option>
                    <option value="Architecture & Code">Architecture & Code</option>
                    <option value="Reports & QA">Reports & QA</option>
                    <option value="Invoices & Legal">Invoices & Legal</option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-mono text-purple-300 uppercase tracking-wider mb-1.5">
                    Format Type
                  </label>
                  <select
                    value={uploadType}
                    onChange={(e) => setUploadType(e.target.value as any)}
                    className="w-full px-3 py-2 rounded-xl bg-neutral-950 border border-purple-900/50 text-white text-xs focus:outline-none"
                  >
                    <option value="pdf">PDF Document</option>
                    <option value="figma">Figma Link</option>
                    <option value="doc">Text / Doc</option>
                    <option value="code">Code / JSON</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-mono text-purple-300 uppercase tracking-wider mb-1.5">
                  Description / Context
                </label>
                <textarea
                  rows={3}
                  value={uploadDescription}
                  onChange={(e) => setUploadDescription(e.target.value)}
                  placeholder="Describe the asset for the engineering pod..."
                  className="w-full px-4 py-2.5 rounded-xl bg-neutral-950 border border-purple-900/50 text-white text-xs focus:outline-none focus:border-purple-400"
                />
              </div>

              <button
                type="submit"
                className="w-full py-3 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-semibold text-xs shadow-md shadow-purple-600/30 transition-all cursor-pointer"
              >
                Attach File to Project
              </button>
            </form>
          </div>
        </div>
      )}

      {/* File Preview Modal */}
      {previewingFile && (
        <div
          className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-4"
          onClick={(e) => {
            if (e.target === e.currentTarget) setPreviewingFile(null);
          }}
        >
          <div className="bg-[#0C0620] border border-purple-800/50 rounded-3xl p-6 sm:p-8 max-w-2xl w-full shadow-2xl space-y-6 animate-in fade-in duration-150 relative">
            <button
              onClick={() => setPreviewingFile(null)}
              className="absolute top-5 right-5 p-2 rounded-xl bg-neutral-900 text-neutral-400 hover:text-white"
            >
              <X className="w-5 h-5" />
            </button>

            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <span className="text-xs font-mono text-purple-400 bg-purple-950/80 px-2.5 py-0.5 rounded border border-purple-800/40 font-bold uppercase">
                  {previewingFile.category}
                </span>
                <span className="text-xs text-neutral-400 font-mono">
                  {previewingFile.uploadedAt}
                </span>
              </div>
              <h3 className="text-xl font-bold text-white">{previewingFile.name}</h3>
            </div>

            <div className="p-5 rounded-2xl bg-neutral-950/80 border border-purple-950 space-y-3 font-mono text-xs text-neutral-300 max-h-60 overflow-y-auto">
              <div className="text-neutral-400">--- DELIVERABLE SPECIFICATION ---</div>
              <div>Project: {project.projectName}</div>
              <div>Code: {project.accessCode}</div>
              <div>Client: {project.company} ({project.clientName})</div>
              <div className="pt-2 text-neutral-200">
                {previewingFile.description || 'Verified engineering deliverable signed off by lead systems architect.'}
              </div>
              <div className="text-emerald-400 pt-2 flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4" />
                <span>Cryptographically verified & IP transfer compliant</span>
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-2">
              <button
                onClick={() => setPreviewingFile(null)}
                className="px-4 py-2.5 rounded-xl bg-neutral-900 text-neutral-300 text-xs font-semibold hover:bg-neutral-800 cursor-pointer"
              >
                Close Preview
              </button>
              <button
                onClick={() => {
                  handleDownloadSimulated(previewingFile);
                  setPreviewingFile(null);
                }}
                className="px-5 py-2.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold flex items-center gap-2 cursor-pointer shadow-md shadow-purple-600/30"
              >
                <Download className="w-4 h-4" />
                <span>Download Spec</span>
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
